name: release

# Only trigger, when the build workflow succeeded
on:
  push:
    branches:
      - master
      - release/**

env:
  SYNC_TAG_NAME: 3.4.0-A1
  HOSTED_ZONE: dev.envalfresco.com
  KEEP_ENV: false
  TAS_SCRIPTS: ../alfresco-community-repo/packaging/tests/scripts
  TAS_ENVIRONMENT: ./packaging/tests/environment
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  BRANCH_NAME: ${{ github.ref_name }}
  GIT_PASSWORD: ${{ secrets.BOT_GITHUB_TOKEN }}
  GIT_EMAIL: ${{ secrets.BOT_GITHUB_EMAIL }}
  GIT_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
  S3_BUCKET_REGION: "us-east-1"
  S3_BUCKET2_NAME: "travis-ags-worm-b2"
  ALFRESCO_URL: "http://localhost:8080/alfresco/"
  SHARE_URL: "http://localhost:8181/share"
  DISPLAY: :99.0
  WEBDRIVER_ARGUMENTS: '-Dwebdriver.local.grid=true -Dwebdriver.browser=RemoteFireFox -Dwebdriver.localGrid=false -Dorg.alfresco.rm.timeout_seconds.MEDIUM=30'
  ALF_PWD: ${{ secrets.ALF_PWD }}
  ARTIFACTS_BUCKET: ${{ secrets.ARTIFACTS_BUCKET }}
  ARTIFACTS_KEY: ${{ secrets.ARTIFACTS_KEY }}
  ARTIFACTS_SECRET: ${{ secrets.ARTIFACTS_SECRET }}
  MASTER_URL: ${{ secrets.MASTER_URL }}
  SSL_CERT: ${{ secrets.SSL_CERT }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  CLUSTER_NAME: "acs-cluster"
  RANCHER2_URL: ${{ secrets.RANCHER2_URL }}
  RANCHER2_ACCESS_KEY: ${{ secrets.RANCHER2_ACCESS_KEY }}
  RANCHER2_SECRET_KEY: ${{ secrets.RANCHER2_SECRET_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACS_CLUSTER_AWS_ACCESS_KEY_ID: ${{ secrets.ACS_CLUSTER_AWS_ACCESS_KEY_ID }}
  ACS_CLUSTER_AWS_SECRET_ACCESS_KEY: ${{ secrets.ACS_CLUSTER_AWS_SECRET_ACCESS_KEY }}
  AGS_AWS_ACCESS_KEY_ID: ${{ secrets.AGS_AWS_ACCESS_KEY_ID }}
  AGS_AWS_SECRET_ACCESS_KEY: ${{ secrets.AGS_AWS_SECRET_ACCESS_KEY }}
  GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 90

jobs:
  alfresco_enterprise_share:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: [alfresco_enterprise_share]
    if: >
      (!contains(github.event.head_commit.message, '[no release]')
      && inputs.commitMessage != '[no release]')
      &&
      (github.ref_name == 'master' || startsWith(github.ref_name, 'release/'))
      &&
      github.event_name != 'pull_request'
      &&
      github.event.repository.fork == false
      &&
      !(failure() || cancelled())
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v7.1.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v7.1.0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: "Init"
        run: bash scripts/ci/init.sh
      - name: "Prepare before Test"
        run: |
          pip3 install requests pytest==6.2.4 pytest-testinfra==6.3.0 jmespath==0.10.0
      - name: Install dependencies
        run: mvn -B -V install -DskipTests=true -Dmaven.javadoc.skip=true
      - name: Verify release tag
        run: bash scripts/ci/verify_release_tag.sh
      - name: Get branch name
        uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@v7.1.0
      - name: Release to Nexus
        run: bash scripts/ci/maven_release.sh

  update_downstream:
    runs-on: ubuntu-latest
    needs: release
    if: >
      (!contains(github.event.head_commit.message, '[no downstream]')
      && inputs.commitMessage != '[no downstream]')
      &&
      (github.ref_name == 'master' || startsWith(github.ref_name, 'release/'))
      &&
      github.event_name != 'pull_request'
      &&
      github.event.repository.fork == false
      &&
      !(failure() || cancelled())
    steps:
      - uses: actions/checkout@v4
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v7.1.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v7.1.0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: "Init"
        run: bash scripts/ci/init.sh
      - name: "Prepare before Test"
        run: |
          pip3 install requests pytest==6.2.4 pytest-testinfra==6.3.0 jmespath==0.10.0
      - name: Get branch name
        uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@v7.1.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/configure-git-author@v7.1.0
        with:
          username: ${{ env.GIT_USERNAME }}
          email: ${{ env.GIT_EMAIL }}
          global: true
      - name: Execute update-downstream script
        run: bash scripts/ci/update_downstream.sh

  mirroring:
    runs-on: ubuntu-latest
    needs: update_downstream
    if: >
      (!contains(github.event.head_commit.message, '[no mirror]')
      && inputs.commitMessage != '[no mirror]')
      &&
      (github.ref_name == 'master' || startsWith(github.ref_name, 'release/'))
      &&
      github.event_name != 'pull_request'
      &&
      github.event.repository.fork == false
      &&
      !(failure() || cancelled())
    steps:
      - uses: actions/checkout@v4
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v7.1.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v7.1.0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: "Init"
        run: bash scripts/ci/init.sh
      - name: "Prepare before Test"
        run: |
          pip3 install requests pytest==6.2.4 pytest-testinfra==6.3.0 jmespath==0.10.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/configure-git-author@v7.1.0
        with:
          username: ${{ env.GIT_USERNAME }}
          email: ${{ env.GIT_EMAIL }}
          global: true
      - name: Mirror to community repository
        run: bash scripts/ci/mirror-community-repo.sh "https://github.com/Alfresco/alfresco-community-share.git"
